### GET ALL
GET http://localhost:3000/api/usuarios

### SAVE  <----- no se usa mas, va el auth 
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "carlos",
  "pais": "Argentina",
  "tipoDocumento": "DNI",
  "documento": 12345678,
  "fechaNacimiento": "1970-05-15",
  "contacto": ["carlosxd@example.com", "+5491112345678"]
}


###ID
@id = 10

### GET ONE
GET http://localhost:3000/api/usuarios/{{id}}

### UPDATE
PATCH http://localhost:3000/api/usuarios/{{id}}
Content-Type: application/json

{
  "nombre": "Hola",
  "pais": "Argentina",
  "contacto": ["yosoyyuri@lol.rer"]
}

### DELETE
DELETE http://localhost:3000/api/usuarios/{{id}}