### GET ALL
GET http://localhost:3000/api/localidades

### SAVE
POST http://localhost:3000/api/localidades
Content-Type: application/json

{
    "pais": "Argentina",
    "provincia": "Santa Fe",
    "nombre": "Rosario",
    "codigoPostal": 3000
}

###ID
@id = 2

### GET ONE
GET http://localhost:3000/api/localidades/{{id}}

### UPDATE

PUT http://localhost:3000/api/localidades/{{id}}
Content-Type: application/json

{
  "pais": "Argentina",
  "provincia": "Santa Fe",
  "nombre": "Rosario",
  "codigoPostal": 3000
}

### PATCH

PATCH http://localhost:3000/api/localidades/{{id}}
Content-Type: application/json

{
  "pais": "Chile"
}

### DELETE
DELETE http://localhost:3000/api/localidades/{{id}}