### LOGIN
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "nombreUsuario": "carlos123",
  "contraseña": "carlos123"
}

### OBTENER EL TOKEN AUTOMATICAMENTE DE LA RESPUESTA
@token = {{login.response.body.data.token}}
@id = {{login.response.body.data.usuario.id}}

### GET ONE
GET http://localhost:3000/api/usuarios/{{id}}
Authorization: Bearer {{token}}

### REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "Juan",
  "nombreUsuario": "juan123",
  "pais": "Argentina",
  "fechaNacimiento": "1970-05-15",
  "tipoDocumento": "DNI",
  "documento": 12345678,
  "contraseña": "carlos123",
  "rol": "ADMIN"
}
