### LOGIN
# @name login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "nombreUsuario": "admin@admin.com",
  "contraseña": "123456"
}

### OBTENER EL TOKEN AUTOMATICAMENTE DE LA RESPUESTA
@token = {{login.response.body.data.token}}
@id = {{login.response.body.data.usuario.id}}

### GET ONE
GET http://localhost:3000/api/usuarios/{{id}}
Authorization: Bearer {{token}}

### REGISTER
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "nombre": "todos",
  "nombreUsuario": "cli@cliente.com",
  "pais": "Argentina",
  "fechaNacimiento": "1971-04-25",
  "tipoDocumento": "DNI",
  "documento": 22726100,
  "contraseña": "123456",
  "rol": "CLIENTE"
}
